# Case study and problems

In [ ]:
!head cric_data-200320-181217.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216





1.   Find mean, median, IQR for Sachin, Rahul, and India
2.   Find the histogram of Sachin's scores with 10 bins
3.   Find mean of Sachin's scores grouped by 25 matches
4.   Find mean of Sachin's scores where he has scored a century
5.   Find mean of Sachin's scores when Rahul has scored less than 10
6.   Find mean for Sachin's scores based on which quartile India's score falls in
7.   For every match find out who has has scored more - Sachin or Rahul
8.   How many more runs does Sachin score on average after having scored x runs
9.   How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...



## problem1

In [ ]:
import numpy as np


In [ ]:
cric = np.loadtxt( "cric_data-200320-181217.tsv" , skiprows= 1 , usecols= (1 , 2,3 ))

In [ ]:
cric

array([[100.,  78., 342.],
       [ 11.,  62., 191.],
       [  8.,  85., 252.],
       [ 71.,  24., 307.],
       [104.,  17., 229.],
       [ 18., 104., 246.],
       [  8.,  76., 226.],
       [ 86.,  74., 288.],
       [ 12.,  60., 216.],
       [ 85.,  12., 224.],
       [ 18.,  63., 161.],
       [  4., 107., 276.],
       [  7.,  76., 283.],
       [ 37.,   4., 297.],
       [ 14.,   5., 139.],
       [  0.,  33., 224.],
       [  4.,   7., 178.],
       [  0.,   0.,   0.],
       [ 21.,  36., 193.],
       [  1.,  66., 231.],
       [ 62.,   0., 134.],
       [  0., 123., 246.],
       [138.,  39., 299.],
       [ 38.,   9., 242.],
       [  2.,  11., 214.],
       [ 46.,  14., 152.],
       [ 65.,   0., 104.],
       [  0.,   0.,   4.],
       [ 39.,  26., 155.],
       [ 48.,   4., 168.],
       [141.,  48., 282.],
       [ 62.,   7., 228.],
       [ 12.,  73., 231.],
       [  1.,  86., 238.],
       [ 41.,  32., 255.],
       [ 11.,  82., 273.],
       [  3.,  25., 143.],
 

In [ ]:
cric.shape

(225, 3)

In [ ]:
sachin_score = cric[ : , 0]

In [ ]:
rahul_score = cric[ : ,1 ]

In [ ]:
india_score = cric[ : , 2]

In [ ]:
def stats(col):
    print("mean : ",np.mean(col))
    print("median: ",np.median(col))
    print("IQR: ", np.percentile(col, 75) - np.percentile(col, 25))

In [ ]:
stats(sachin_score)

mean :  39.87555555555556
median:  27.0
IQR:  57.0


In [ ]:
stats(rahul_score)

mean :  32.062222222222225
median:  22.0
IQR:  46.0


In [ ]:

stats(india_score)

mean :  220.79555555555555
median:  216.0
IQR:  98.0


In [ ]:

np.mean(cric , axis= 0) # alternative and more efficient method

array([ 39.87555556,  32.06222222, 220.79555556])

In [ ]:
np.median(cric , axis= 0)

array([ 27.,  22., 216.])

In [ ]:
np.percentile( cric , 75 , axis=0) - np.percentile( cric , 25 , axis= 0)

array([57., 46., 98.])

##problem 2

In [ ]:

np.histogram(sachin_score)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [ ]:

sachin_score.shape

(225,)

In [ ]:

sachin_score.ndim

1

In [ ]:
sachin = sachin_score.reshape(9,25)

In [ ]:
sachin.shape

(9, 25)

In [ ]:
sachin.ndim

2

In [ ]:
np.mean(sachin , axis= 1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

## problem 4 & 5

In [ ]:
np.mean(sachin[sachin>= 100])


125.0

In [ ]:
np.mean(sachin_score[rahul_score <= 10 ])

40.2112676056338


## problem 6 & 7

In [ ]:
qrt = np.percentile( india_score , [25,50,75,100])

In [ ]:

india_score.shape

(225,)

In [ ]:
qrt.shape # here india_score and qrt are of diff sizes and cannot be broadcasted acc to rules thus we reshape qrt

(4,)

In [ ]:
qrt = qrt.reshape(4,1)

In [ ]:
indices = india_score < qrt

In [ ]:
indices.shape

(4, 225)

In [ ]:
sachin_score[indices[ 0 , : ]]

array([18., 14.,  0., 62., 46., 65.,  0., 39., 48.,  3., 11., 65., 27.,
       28.,  3.,  4., 15., 40.,  5.,  8., 89.,  0.,  0.,  1.,  0.,  0.,
       81., 13.,  2., 36., 12., 19.,  0.,  6., 35.,  0., 44.,  3., 47.,
       17., 35., 33.,  7.,  9.,  2., 11., 17.,  1., 10.,  0., 23.,  1.,
        2., 25.,  0.])

In [ ]:
for i in range (4):
    print( i , np.mean(sachin_score[indices[i]]))

0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146


## problem 7

In [ ]:
snr = cric[ : , 0:2]

In [ ]:
np.argmax( snr , axis= 1)

6