In [ ]:
N = 100000

In [ ]:
%%time
list_  = list(range(N))
for i in range(N):
    list_[i]  = list_[i]* list_[i]


CPU times: user 28.8 ms, sys: 759 µs, total: 29.5 ms
Wall time: 29.5 ms


In [ ]:
%%time
list_ = list(range(N))
list_  = [item*  item for item in list_  ]  

CPU times: user 7.73 ms, sys: 2.99 ms, total: 10.7 ms
Wall time: 11 ms


In [ ]:
%%time
list_ = list(range(N))
list_ = map(lambda x : x*x  , list_)


CPU times: user 580 µs, sys: 1.91 ms, total: 2.49 ms
Wall time: 2.5 ms


In [ ]:
%%time
list_  = list(range(N))
list_sum  = sum(list_  )


CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 10.3 µs


# **importing**

In [ ]:
import numpy as np


In [ ]:
%%time
arr  = np.arange(N)
arr_sum  =  np.sum(arr)

CPU times: user 632 µs, sys: 30 µs, total: 662 µs
Wall time: 4.86 ms


## creating np  arrays


In [ ]:
arr =  np.arange(5)  # 1st to create
print( arr)

[0 1 2 3 4]


In [ ]:
arr = np.array([0,2,4,6])  #  2nd way
print(arr)


[0 2 4 6]


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(4,)

In [ ]:
arr.size

4

In [ ]:
arr.itemsize  # no. of byts  required to store  the  item


8

# 2d array

In [ ]:
arr2d = np.array( [ [1,2,3.5],
                   [4,3.6,8]
])

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d.itemsize

8

In [ ]:
arr2d.size

6

#  3d array

In [ ]:
arr3d  =  np.array([[[1,2,3],
                    [1,2,3]
                    ],  
                   [[1,2,3] ,
                    [1,2,3]
                   ]])

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr3d.size

12

In [ ]:
arr3d.itemsize

8

# 4d array

In [ ]:
np.ones((2,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [ ]:
3 * np.ones((2,3,4))

array([[[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# random

In [ ]:
np.random.randn( 2, 3 )      # gives matrix where each of these numbers are randomly  sampled  from a normal distribution with mean=0 & var = 1

array([[-1.13940621,  0.35662278,  0.10547106],
       [ 0.10704665, -0.4644042 ,  1.35690227]])

In [ ]:
np.random.rand(2,3)  # gives numbers uniformly sampled btwn 0 &1

array([[0.92488445, 0.27141604, 0.64640264],
       [0.24073585, 0.21834054, 0.24818227]])

In [ ]:
np.random.randint(0,100,(2,3))

array([[64, 44, 33],
       [79, 55, 93]])

In [ ]:
np.arange(7,30,7)

array([ 7, 14, 21, 28])

In [ ]:
np.linspace(1,20,8)

array([ 1.        ,  3.71428571,  6.42857143,  9.14285714, 11.85714286,
       14.57142857, 17.28571429, 20.        ])

# indexing

In [ ]:
arr3d  =  np.array([[[1,2,3],
                    [4,5,6]
                    ],  
                   [[7,8,9] ,
                    [10,11,12]
                   ]])

In [ ]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr3d[0,0,0]

1

In [ ]:
arr3d[1,1,1]


11

In [ ]:
arr3d[0,1,2]

6

In [ ]:
arr3d[0,: , :]


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3d[1,:  , : ]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr3d[:  , 1 , :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
arr3d[0,1,0:2]  

array([4, 5])

In [ ]:
arr3d % 2 == 0   # to find even numbers in array

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [ ]:
arr3d[ arr3d % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr3d [ arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
arr3d [ (arr3d % 2 == 1) & (arr3d > 5)]

array([ 7,  9, 11])

In [ ]:
arr3d [ 0, 1, 1] = 1729  # changing the value in array

In [ ]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# numPy operations

In [ ]:
import numpy as np


In [ ]:
arr1 = np.random.rand(3,4)
arr2 = np.random.rand(3,4)

In [ ]:
arr1


array([[0.97078166, 0.59029334, 0.83577159, 0.64049664],
       [0.15078806, 0.60159674, 0.57383941, 0.52238716],
       [0.414586  , 0.96694828, 0.41167208, 0.50574762]])

In [ ]:
arr2

array([[0.12905781, 0.09465357, 0.92647146, 0.5941849 ],
       [0.05480694, 0.89593815, 0.87955714, 0.96923683],
       [0.55414573, 0.13444409, 0.78742503, 0.79088755]])

In [ ]:
arr1 + arr2

array([[1.09983947, 0.68494691, 1.76224305, 1.23468154],
       [0.205595  , 1.49753489, 1.45339655, 1.49162399],
       [0.96873172, 1.10139237, 1.19909711, 1.29663517]])

In [ ]:
arr1 * arr2

array([[0.12528696, 0.05587337, 0.77431852, 0.38057343],
       [0.00826423, 0.53899347, 0.50472455, 0.50631687],
       [0.22974106, 0.13000048, 0.3241609 , 0.3999895 ]])

In [ ]:
arr1 / arr2

array([[7.5220681 , 6.23635592, 0.90210182, 1.07794163],
       [2.75125856, 0.67147129, 0.65241856, 0.53896751],
       [0.74815338, 7.19219603, 0.52280796, 0.63946843]])

# Exercise on n- dimensional array

In [ ]:
ndim = 2
npoints = 100000
points = np.random.rand( npoints , ndim)

In [ ]:
points.ndim

2

In [ ]:
points[ 0:2 , :]

array([[0.1593846 , 0.95035179],
       [0.74933035, 0.22137586]])

In [ ]:
dfo = np.zeros((npoints, 1))

In [ ]:
print(dfo)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [ ]:
points_sqr = points * points
dfo  = np.sqrt(np.sum( points_sqr , axis = 1))
outside_points = np.sum(  dfo > 1)
print( " the fraction of points outside is " , outside_points/ npoints)

 the fraction of points outside is  0.21581


In [ ]:
def  area_outside(  npoints ,  ndim ):
    points = np.random.rand(  npoints,  ndim)
    dfo  =  np.sqrt( np.sum( points * points , axis= 1))
    return np.sum( dfo >  1) / npoints

In [ ]:
print( area_outside(100000,2) )

0.21369


In [ ]:
for i in range(2,11):
    print(i , area_outside(npoints , i))

2 0.2128
3 0.47785
4 0.69304
5 0.83549
6 0.91941
7 0.96348
8 0.98414
9 0.99373
10 0.99751


#  Broadcasting

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

they are equal, or

one of them is 1

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

In [ ]:
arr1 = np.arange(8)

In [ ]:
print(arr1)

[0 1 2 3 4 5 6 7]


In [ ]:
print( arr1.ndim)

1


In [ ]:
arr1_new = arr1.reshape(2,2,2)

In [ ]:
print(arr1_new)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
arr2 = np.arange(8).reshape(2,2,2)

In [ ]:
print( arr1_new +  arr2)   

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]


In [ ]:
arr2[ : ,  0]

array([[0, 1],
       [4, 5]])

In [ ]:
arr1_new + arr2[: , 0]  #  broacasting arr1_new (2,2,2) + arr2 ( 1,2,2)

array([[[ 0,  2],
        [ 6,  8]],

       [[ 4,  6],
        [10, 12]]])

In [ ]:
arr2[1,1,  :].reshape(2,1)

array([[6],
       [7]])

In [ ]:
arr1_new + arr2[1,1,  :].reshape(2,1)  #  arr1_new( 2, 2,2) + arr2 (2,1)

array([[[ 6,  7],
        [ 9, 10]],

       [[10, 11],
        [13, 14]]])

In [ ]:
arr1 = np.arange(9) 

In [ ]:
print(arr1)

# file handling

#  Stats with numpy

In [ ]:
import numpy as np


In [ ]:
arr = np.random.rand(100000,)

In [ ]:
arr

array([0.48158519, 0.63656036, 0.5863072 , ..., 0.23011973, 0.00177181,
       0.07937489])

In [ ]:
np.amin(arr)

3.3529582968983007e-06

In [ ]:
np.amax(arr)

0.9999994505849258

In [ ]:
np.mean(arr)

0.500579433026447

In [ ]:
np.var(arr)

0.08335360085409024

In [ ]:
np.std(arr)

0.28871023683633085

In [ ]:
np.median(arr)

0.5013780498050175

In [ ]:

arr.ndim

1

In [ ]:
np.percentile(arr, 50)

0.5013780498050175

In [ ]:

Iqr = np.percentile(arr,75) - np.percentile(arr , 25) # inter quartile range

In [ ]:
Iqr

0.5000273483608872

In [ ]:
quartiles = np.percentile( arr , [25, 75]) # this part takes less time than the previous one

In [ ]:
quartiles

array([0.25033008, 0.75035743])

In [ ]:
iqr = quartiles[1] - quartiles[0]

In [ ]:
iqr


-0.5000273483608872

In [ ]:
z_scores =  arr - (np.mean(arr)/ np.std(arr))

In [ ]:
z_scores

array([-1.252262  , -1.09728683, -1.14753999, ..., -1.50372746,
       -1.73207538, -1.6544723 ])

In [ ]:
np.histogram( arr , bins = 5)

(array([19962, 19993, 19941, 20023, 20081]),
 array([3.35295830e-06, 2.00002572e-01, 4.00001792e-01, 6.00001012e-01,
        8.00000231e-01, 9.99999451e-01]))

In [ ]:
arr1= np.random.randint(150 , 180 , 100) # height

In [ ]:
arr2 = np.random.randint(40 , 80 , 100) # weight

In [ ]:
arr3 = np.random.randint(17, 22 , 100) # age

In [ ]:
arr1

array([158, 176, 159, 167, 161, 155, 160, 164, 152, 168, 155, 154, 160,
       162, 172, 176, 172, 164, 178, 165, 160, 172, 167, 175, 162, 159,
       164, 171, 165, 168, 164, 172, 176, 172, 172, 155, 174, 150, 174,
       169, 158, 175, 156, 154, 173, 158, 159, 164, 178, 156, 156, 167,
       173, 172, 159, 164, 170, 176, 175, 150, 177, 158, 178, 150, 177,
       174, 178, 164, 158, 171, 174, 169, 160, 157, 155, 171, 167, 157,
       154, 157, 165, 150, 150, 178, 176, 168, 175, 179, 162, 168, 158,
       163, 173, 156, 171, 175, 151, 175, 153, 151])

In [ ]:
np.concatenate( ( arr1 , arr2 , arr3) )

array([158, 176, 159, 167, 161, 155, 160, 164, 152, 168, 155, 154, 160,
       162, 172, 176, 172, 164, 178, 165, 160, 172, 167, 175, 162, 159,
       164, 171, 165, 168, 164, 172, 176, 172, 172, 155, 174, 150, 174,
       169, 158, 175, 156, 154, 173, 158, 159, 164, 178, 156, 156, 167,
       173, 172, 159, 164, 170, 176, 175, 150, 177, 158, 178, 150, 177,
       174, 178, 164, 158, 171, 174, 169, 160, 157, 155, 171, 167, 157,
       154, 157, 165, 150, 150, 178, 176, 168, 175, 179, 162, 168, 158,
       163, 173, 156, 171, 175, 151, 175, 153, 151,  56,  73,  45,  62,
        52,  68,  79,  75,  79,  66,  70,  65,  69,  71,  70,  75,  49,
        79,  77,  45,  58,  56,  43,  47,  77,  70,  55,  46,  65,  55,
        57,  56,  62,  71,  72,  55,  64,  72,  55,  54,  49,  55,  52,
        44,  40,  71,  48,  47,  72,  58,  55,  63,  48,  78,  71,  78,
        61,  79,  57,  49,  73,  59,  73,  66,  58,  71,  47,  61,  61,
        79,  40,  64,  54,  47,  46,  62,  47,  69,  66,  40,  7

In [ ]:
arr2d = np.vstack((arr1 , arr2 , arr3 ))

In [ ]:
arr2d

array([[158, 176, 159, 167, 161, 155, 160, 164, 152, 168, 155, 154, 160,
        162, 172, 176, 172, 164, 178, 165, 160, 172, 167, 175, 162, 159,
        164, 171, 165, 168, 164, 172, 176, 172, 172, 155, 174, 150, 174,
        169, 158, 175, 156, 154, 173, 158, 159, 164, 178, 156, 156, 167,
        173, 172, 159, 164, 170, 176, 175, 150, 177, 158, 178, 150, 177,
        174, 178, 164, 158, 171, 174, 169, 160, 157, 155, 171, 167, 157,
        154, 157, 165, 150, 150, 178, 176, 168, 175, 179, 162, 168, 158,
        163, 173, 156, 171, 175, 151, 175, 153, 151],
       [ 56,  73,  45,  62,  52,  68,  79,  75,  79,  66,  70,  65,  69,
         71,  70,  75,  49,  79,  77,  45,  58,  56,  43,  47,  77,  70,
         55,  46,  65,  55,  57,  56,  62,  71,  72,  55,  64,  72,  55,
         54,  49,  55,  52,  44,  40,  71,  48,  47,  72,  58,  55,  63,
         48,  78,  71,  78,  61,  79,  57,  49,  73,  59,  73,  66,  58,
         71,  47,  61,  61,  79,  40,  64,  54,  47,  46,  62,  47,  6

In [ ]:
np.vstack((arr1 , arr2 , arr3 )).shape

(3, 100)

In [ ]:
np.amin( arr2d , axis= 1 ) # min across coloumns  i.e min along each row

array([150,  40,  17])

In [ ]:
np.amin(arr2d  , axis= 1)

array([150,  40,  17])

In [ ]:
np.sum(np.isin(np.amin(arr2d  , axis= 1) , arr2d))

3

In [ ]:
np.amax(arr2d  , axis= 1)

array([179,  79,  21])

In [ ]:
np.mean(arr2d  , axis= 1) # mean height, weight , age

array([165.15,  61.59,  19.16])

# checking stats rules with numpy

## Mean subracted array has zero mean

In [ ]:
arr = np.random.rand(1000)

In [ ]:
mean = np.mean(arr)

In [ ]:
arr1 = arr- mean

In [ ]:
np.mean(arr1)  # value close to zero


2.3092638912203255e-17

## computing mean with smaller set of value 

In [ ]:
arr = np.random.rand( 1000)

In [ ]:
for k in range (1, 50):
    arr1 = arr[ 0: k]
    print(k, np.mean(arr1))

1 0.3596594835584582
2 0.6558894946021088
3 0.45825651152110575
4 0.3753176185015418
5 0.30835461378020945
6 0.3768091202789459
7 0.40952687794119763
8 0.409522424746386
9 0.3964840607911515
10 0.3728093662161447
11 0.39095818062490423
12 0.36387194001111106
13 0.3752786476894852
14 0.4001647201500406
15 0.4277215320599491
16 0.4516485355858679
17 0.4388737936030734
18 0.4341844481560064
19 0.4188465351795118
20 0.4094773419729637
21 0.40883249812277206
22 0.4035332283013356
23 0.4142357621309571
24 0.42515124457532516
25 0.42905209506172637
26 0.42457678998255666
27 0.4125387952907709
28 0.4070009040749735
29 0.4001394732350741
30 0.3989092739743987
31 0.4009906392829884
32 0.40574720003340187
33 0.40405207602272264
34 0.41441403430383544
35 0.42674632254002653
36 0.42551122035494127
37 0.4297100216229362
38 0.4253176087181753
39 0.4166590347041274
40 0.42475618185558295
41 0.42128364647387656
42 0.4333419520001268
43 0.43373290551358473
44 0.43487195757519215
45 0.4315144108225884
46

In [ ]:
np.cumsum?

In [ ]:
means = np.cumsum( arr) / np.arange(1 , 1001)

In [ ]:
means[0:50] # 1st 50 means

array([0.35965948, 0.65588949, 0.45825651, 0.37531762, 0.30835461,
       0.37680912, 0.40952688, 0.40952242, 0.39648406, 0.37280937,
       0.39095818, 0.36387194, 0.37527865, 0.40016472, 0.42772153,
       0.45164854, 0.43887379, 0.43418445, 0.41884654, 0.40947734,
       0.4088325 , 0.40353323, 0.41423576, 0.42515124, 0.4290521 ,
       0.42457679, 0.4125388 , 0.4070009 , 0.40013947, 0.39890927,
       0.40099064, 0.4057472 , 0.40405208, 0.41441403, 0.42674632,
       0.42551122, 0.42971002, 0.42531761, 0.41665903, 0.42475618,
       0.42128365, 0.43334195, 0.43373291, 0.43487196, 0.43151441,
       0.43134942, 0.43673123, 0.43227851, 0.43852185, 0.43794933])

## effect of outliers on mean and median

In [ ]:
arr = np.random.randint(1 , 100, 100)

In [ ]:
np.mean( arr )

47.49

In [ ]:
np.median(arr)

42.0

In [ ]:
arr = np.append( arr , [ 1000 , 2000])

In [ ]:
arr.shape

(102,)

In [ ]:
np.mean(arr)

75.97058823529412

In [ ]:
np.median(arr) # median is robust to outliers

42.5

## Effect of scaling arrays on mean and median

In [ ]:
arr = np.random.rand(100)

In [ ]:
np.mean( arr)

0.49137703390711995

In [ ]:
np.median( arr)

0.4919516576682751

In [ ]:
arr1 = 2.5 * arr + 0.6 # scaling 

In [ ]:
print ( np.mean(arr1) , 2.5 * np.mean(arr) + 0.6 )

1.8284425847678 1.8284425847677999


In [ ]:
print ( np.var ( arr1 ) , 2.5 *2.5 * np.var(arr))

0.4539113735402394 0.45391137354023925


# important functions

In [ ]:
np.argmax ([ 1,2,3,4,5,6])  # ell the index value of max value

5

In [ ]:
np.max([ 1,2,3,4,5,6])

6